version: '{build}'

image: Visual Studio 2017
configuration: Release
skip_tags: true

before_build:
- ps: nuget restore

build:
  verbosity: minimal

artifacts:
- path: CliWrap\bin\$(configuration)\CliWrap*.nupkg
  name: CliWrap.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: QuL5btMfw2HUtOrAO0C8hw0ILWLAY9Tq4Gp1uuDiPCjkOt7H8glITwlPCxoB/WWA
  artifact: CliWrap.nupkg
  on:
    branch: master
    APPVEYOR_REPO_COMMIT_MESSAGE: "Update version"
    APPVEYOR_REPO_COMMIT_AUTHOR: "Alexey Golub"
